version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: my-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: dikma
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
